### ISSUE TITLE
Contact with you ? 

### ISSUE THREAD

**Issue by zilveer** [jxy918/swoole-game#2]
Hi,
How can I get in touch with you, do you have Skype or email I can contact you ?
It is about game development.
Sorry saw your Qq, just sent an apply request to you there.
Hope you can accept me

Regards

**Comment by jxy918** [comment]
What is the name of your QQ request?
QQ applicants too many, do not know that?

**Comment by zilveer** [comment]
@jxy918
My QQ number is 669705131, please add me if possible.
