### ISSUE TITLE
ProtobufMessage 不在php扩展protobuf包里

### ISSUE THREAD

**Issue by bimoQi** [jxy918/swoole-game#3]
protobuf这个php扩展包里根本没有ProtobufMessage这个类
只有到https://github.com/allegro/php-protobuf这个库里找到
但是次项目右没有引用 我怎么也跑不起来

**Comment by jxy918** [comment]
probuff这块比较老版本的,  新版本的porotobuf估计跑不起来, protobuf那块主要是为了演示一下tcp协议, 前后端交互, 如果只是跑游戏websocket, 不用去管他, 这个写的比较原生, 这个项目已经用swoft框架重构了, 可以关注swoft-game

**Comment by bimoQi** [comment]
enen 已经看swoft-game了
谢谢
